In [2]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np


Using TensorFlow backend.


In [0]:
from sklearn.model_selection import train_test_split

In [4]:
ip=np.array([[1,0,1]])
op=np.array([[1,0]])
print(ip)
print(op)

[[1 0 1]]
[[1 0]]


In [5]:
model=Sequential()
h1=model.add(Dense(2,activation="sigmoid",input_dim=3))
h2=model.add(Dense(3,activation="sigmoid"))
o = model.add(Dense(2,activation="sigmoid"))

W0827 06:05:47.001923 140516520679296 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0827 06:05:47.052598 140516520679296 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0827 06:05:47.062975 140516520679296 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [7]:
weight_layer1=np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
bias1=np.array([-0.4,0.2])
l=[]
l.append(weight_layer1)
l.append(bias1)
model.layers[0].set_weights(l)
model.layers[0].get_weights()

W0827 06:06:32.382838 140516520679296 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0827 06:06:32.384808 140516520679296 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



[array([[ 0.2, -0.3],
        [ 0.4,  0.1],
        [-0.5,  0.2]], dtype=float32), array([-0.4,  0.2], dtype=float32)]

In [8]:
weight_layer2=np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2]])
bias2=np.array([0.1,0.1,0.2])
l=[]
l.append(weight_layer2)
l.append(bias2)
model.layers[1].set_weights(l)
model.layers[1].get_weights()

[array([[-0.3,  0.2,  0.6],
        [-0.2, -0.1, -0.2]], dtype=float32),
 array([0.1, 0.1, 0.2], dtype=float32)]

In [9]:
weight_layer3=np.array([[0.3,0.2],[-0.5,0.5],[-0.7,0.2]])
bias3=np.array([0.1,0.2])
l=[]
l.append(weight_layer3)
l.append(bias3)
model.layers[2].set_weights(l)
model.layers[2].get_weights()

[array([[ 0.3,  0.2],
        [-0.5,  0.5],
        [-0.7,  0.2]], dtype=float32), array([0.1, 0.2], dtype=float32)]

**USING MEAN ABSOLUTE ERROR LOSS FUNCTION**

In [0]:
from keras import optimizers
optimizers.Adam(lr=0.9)
model.compile(loss="mean_absolute_error",optimizer="Adam",metrics=['accuracy'])

In [32]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 9         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 8         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.fit(ip,op,batch_size=1,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 2ms/step - loss: 0.5229 - acc: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 2ms/step - loss: 0.5222 - acc: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 2ms/step - loss: 0.5215 - acc: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 2ms/step - loss: 0.5208 - acc: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 1ms/step - loss: 0.5200 - acc: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 1ms/step - loss: 0.5193 - acc: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 1ms/step - loss: 0.5186 - acc: 0.0000e+00
Epoch 8/10
1/1 [==============================] - 0s 2ms/step - loss: 0.5178 - acc: 0.0000e+00
Epoch 9/10
1/1 [==============================] - 0s 2ms/step - loss: 0.5171 - acc: 0.0000e+00
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 0.5164 - acc: 0.0000e+00


**USING MEAN SQUARED ERROR LOSS FUNCTION**

In [0]:
from keras import optimizers
optimizers.Adam(lr=0.9)
model.compile(loss="mean_squared_error",optimizer="Adam",metrics=['accuracy'])

In [36]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 9         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 8         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.fit(ip,op,batch_size=1,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 338ms/step - loss: 0.2676 - acc: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 2ms/step - loss: 0.2670 - acc: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 2ms/step - loss: 0.2664 - acc: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 1ms/step - loss: 0.2657 - acc: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 1ms/step - loss: 0.2650 - acc: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 1ms/step - loss: 0.2643 - acc: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 1ms/step - loss: 0.2636 - acc: 0.0000e+00
Epoch 8/10
1/1 [==============================] - 0s 1ms/step - loss: 0.2629 - acc: 0.0000e+00
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 0.2621 - acc: 0.0000e+00
Epoch 10/10
1/1 [==============================] - 0s 1ms/step - loss: 0.2614 - acc: 0.0000e+00
